---
- name: Ensure iptables is installed (RedHat).
  yum: pkg=iptables state=installed
  when: ansible_os_family == 'RedHat'

- name: Ensure iptables is installed (Debian).
  apt: pkg=iptables state=installed
  when: ansible_os_family == 'Debian'

- name: Flush iptables the first time playbook runs.
  command: iptables -F creates=/etc/init.d/firewall

- name: Copy firewall script into place.
  template: src=firewall.bash.j2 dest=/etc/firewall.bash owner=root group=root mode=0744
  notify: restart firewall

- name: Copy firewall init script into place.
  template:
    src: firewall.init.j2
    dest: /etc/init.d/firewall
    owner: root
    group: root
    mode: 0755

- name: Copy firewall systemd unit file into place (for systemd systems).
  template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0755
  when: >
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04') or
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 8) or
    (ansible_distribution == 'CentOS' and ansible_distribution_version|int >= 7) or
    (ansible_distribution == 'Fedora')

- name: Ensure the firewall is enabled and will start on boot.
  service: name=firewall state=started enabled=yes
