---
- name: Converge
  hosts: all
  become: true

  vars:
    firewall_allowed_tcp_ports:
      - "1234"
    firewall_allowed_udp_ports:
      - "5678"
    firewall_forwarded_tcp_ports:
      - src: 22
        dest: 2222
    firewall_forwarded_udp_ports:
      - src: 33
        dest: 3333
    firewall_additional_rules:
      - "iptables -A INPUT -p tcp --dport 4949 -s 192.168.1.1 -j ACCEPT"


  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=1200
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: schoeppe.firewall
